language: objective-c 
osx_image: xcode7.3

script:
  - xcodebuild clean test -workspace "Example/LHToolbar.xcworkspace" -scheme "LHToolbar_Tests" -sdk "iphonesimulator9.3" -destination "OS=9.0,name=iPhone 6 Plus" -configuration Debug ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c

