language: objective-c 
osx_image: xcode7.3

script:
  - xcodebuild clean test -workspace "LHToolbarDemo.xcworkspace" -scheme "LHToolbarTests" -sdk "iphonesimulator9.3" -destination "OS=9.0,name=iPhone 6 Plus" -configuration Debug ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
  - cd LHToolbarDemoCocoaPodsTest/
  - pod install
  - cd ..
  - pod lib lint --allow-warnings

after_success:
  - bash <(curl -s https://codecov.io/bash) -J LHToolbar
